### ISSUE TITLE
Make a help function

### ISSUE THREAD

**Issue by koreaneggroll** [midnqp/lib-cpythonbuiltins#18]
Make a help function that prints out every function available in the file and also saying what it does and how it should be used.

**Comment by midnqp** [comment]
At this stage you might be under the illusion that this repository gets nothing into the mainstream. The truth is, `help()` are mainly for learning in an interpreter. In C, we don't get an interpreter. Some implementations, however, do exist respectfully with their own issues. But, honestly and speaking evenly, @koreaneggroll , 
I always emphasize & appreciate your efforts to contribution. But `help()` prints stuffs to the stdout. And I don't see a critical use case of it. 

The function-names are self-explanatory. README already provides arguments, and the code is well-documented without bloats.
